internlm2_5-7b-hf:
    demo_gsm8k: 42.19
    race-middle: 91.78
    race-high: 90.02

internlm2_5-7b_hf:
    demo_gsm8k: 42.19
    race-middle: 91.78
    race-high: 90.02

internlm2-1.8b-hf:
    demo_gsm8k: 15.62
    race-middle: 71.66
    race-high: 66.38

internlm2_5-7b-chat-lmdeploy:
    demo_gsm8k: 84.38
    race-middle: 92.76
    race-high: 90.54

internlm2-chat-1.8b-lmdeploy:
    demo_gsm8k: 31
    race-middle: 81.34
    race-high: 73.96

internlm2_5-7b-chat_hf:
    demo_gsm8k: 87.50
    race-middle: 92.76
    race-high: 90.48

lmdeploy-api-test:
    gsm8k: 83.78
    race-middle: 92.41
    race-high: 90.37
